// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxfXHLP114ks4NY0uccevQyt4qkiculHE',
    appId: '1:708554638816:web:5b00fac8e1fab649345785',
    messagingSenderId: '708554638816',
    projectId: 'wiskerway-d74c2',
    authDomain: 'wiskerway-d74c2.firebaseapp.com',
    storageBucket: 'wiskerway-d74c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4slOqMZvv738AjnNX8G4EtjBwI2brpmo',
    appId: '1:708554638816:android:b004cfe18cdf0360345785',
    messagingSenderId: '708554638816',
    projectId: 'wiskerway-d74c2',
    storageBucket: 'wiskerway-d74c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoim0XsgQ1EElF_SBZzl2Yrbu9YHoOTew',
    appId: '1:708554638816:ios:26d35e55f61a0c6a345785',
    messagingSenderId: '708554638816',
    projectId: 'wiskerway-d74c2',
    storageBucket: 'wiskerway-d74c2.appspot.com',
    iosBundleId: 'com.example.flutterMobileWhiskerway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoim0XsgQ1EElF_SBZzl2Yrbu9YHoOTew',
    appId: '1:708554638816:ios:26d35e55f61a0c6a345785',
    messagingSenderId: '708554638816',
    projectId: 'wiskerway-d74c2',
    storageBucket: 'wiskerway-d74c2.appspot.com',
    iosBundleId: 'com.example.flutterMobileWhiskerway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxfXHLP114ks4NY0uccevQyt4qkiculHE',
    appId: '1:708554638816:web:b69d13c804ca1e13345785',
    messagingSenderId: '708554638816',
    projectId: 'wiskerway-d74c2',
    authDomain: 'wiskerway-d74c2.firebaseapp.com',
    storageBucket: 'wiskerway-d74c2.appspot.com',
  );
}
